function probedesign
%
% Graphical User Interface to design probes
%
% Usage - call probedesign from Matlab console
%
% Written by Mariagrazia Popeo and Matteo Caffini
% CIMeC - Universita' dgli Studi di Trento
% on September 2nd, 2016 in Rovereto (TN)
%

Hmain = []; % handles to uicontrols and graphics
Hmain.AZ = 0;
Hmain.EL = 0;

%% Set color background
defaultColor = get(0,'DefaultUicontrolBackgroundcolor');

%% Create main figure
screenSize = get(0,'ScreenSize');
figureW = 1000;
figureH = 800;
figurePosition = [screenSize(3)/2-figureW/2 screenSize(4)/2-figureH/2-20 figureW figureH];
Hmain.mainFigure = figure('Position',figurePosition, ...
    'Visible','off',...
    'Units','pixels', ...
    'Resize','on',...
    'Name','probedesign', ...
    'Numbertitle','off', ...
    'Tag','main_figure', ...
    'Color',defaultColor, ...
    'Toolbar','none', ...
    'Menubar','none', ...
    'DoubleBuffer','on', ...
    'DockControls','off',...
    'Renderer','OpenGL');
set(Hmain.mainFigure,'toolbar','figure');
set(Hmain.mainFigure,'menubar','figure');
%% Atlas Visualization Panel
atlasW = 0.75;
atlasH = 0.94;
atlasPosition = [0.03 0.03 atlasW atlasH];
Hmain.atlasPanel = uipanel('Parent',Hmain.mainFigure,...
    'Title','',...
    'FontSize',12,...
    'BackgroundColor',[0 0 0]/255,...
    'Position',atlasPosition);

atlasW = 0.98;
atlasH = 0.98;
atlasPosition = [0.01 0.01 atlasW atlasH];
Hmain.axis = axes('parent',Hmain.atlasPanel,...
    'Units','normalized',...
    'Position', atlasPosition,...
    'XDir','normal','YDir','normal',...
    'Box','off', ...
    'XGrid','off','YGrid','off',...
    'XTickLabel',[],'YTickLabel',[],...
    'Fontsize',6,...
    'Color',[0 0 0]/255,...
    'Box','off',...
    'Visible','on');

%% Rotate view Panel
rotateW = 0.05;
rotateH = 0.3;
rotatePosition = [0 0.7 rotateW rotateH];
Hmain.rotatePanel = uipanel('Parent',Hmain.atlasPanel,...
    'Title','',...
    'FontSize',12,...
    'BackgroundColor',[1 1 1]/255,...
    'BorderType', 'none', ...
    'Position',rotatePosition);

buttonW = 1;
buttonH = 0.16;

buttonPosition = [0 0.04+0.16*(1-1) buttonW buttonH]; %Superior
Hmain.rotateS = uicontrol('parent',Hmain.rotatePanel,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String','S',...
    'HorizontalAlignment','center',...
    'Enable','on',...
    'FontWeight','bold',...
    'FontSize',12,...
    'Position',buttonPosition,...
    'Callback', @rotateS);

buttonPosition = [0 0.04+0.16*(2-1) buttonW buttonH]; %Inferior
Hmain.rotateI = uicontrol('parent',Hmain.rotatePanel,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String','I',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'Position',buttonPosition,...
    'Callback', @rotateI);

buttonPosition = [0 0.04+0.16*(3-1) buttonW buttonH];
Hmain.rotateL = uicontrol('parent',Hmain.rotatePanel,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String','L',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'Position',buttonPosition,...
    'Callback', @rotateL);

buttonPosition = [0 0.04+0.16*(4-1) buttonW buttonH];
Hmain.rotateR = uicontrol('parent',Hmain.rotatePanel,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String','R',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'Position',buttonPosition,...
    'Callback', @rotateR);

buttonPosition = [0 0.04+0.16*(5-1) buttonW buttonH];
Hmain.rotateA = uicontrol('parent',Hmain.rotatePanel,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String','A',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'Position',buttonPosition,...
    'Callback', @rotateA);

buttonPosition = [0 0.04+0.16*(6-1) buttonW buttonH];
Hmain.rotateP = uicontrol('parent',Hmain.rotatePanel,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String','P',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'Position',buttonPosition,...
    'Callback', @rotateP);

%% Checkboxes Panel
optionsW = 0.20;
optionsH = 0.20;
optionsPosition = [0.80 0.80 optionsW optionsH];
Hmain.optionsPanel = uipanel('parent',Hmain.atlasPanel,...
    'Title', 'Options', ...
    'Units','normalized',...
    'FontSize',10,...
    'Position',optionsPosition);
textW = 0.4;
textH = 0.15;
textCoordsPosition = [0.2 0.125 textW textH];
Hmain.optionsCoords = uicontrol('parent',Hmain.optionsPanel,...
    'Style','text',...
    'Units','normalized',...
    'String','Coords',...
    'HorizontalAlignment','left',...
    'FontWeight','bold',...
    'FontSize',10,...
    'Position',textCoordsPosition);
textGMPosition = [0.2 0.125+0.15 textW textH];
Hmain.optionsGM = uicontrol('parent',Hmain.optionsPanel,...
    'Style','text',...
    'Units','normalized',...
    'String','GM',...
    'HorizontalAlignment','left',...
    'FontWeight','bold',...
    'FontSize',10,...
    'Position',textGMPosition);
textWMPosition = [0.2 0.125+2*0.15 textW textH];
Hmain.optionsWM = uicontrol('parent',Hmain.optionsPanel,...
    'Style','text',...
    'Units','normalized',...
    'String','WM',...
    'HorizontalAlignment','left',...
    'FontWeight','bold',...
    'FontSize',10,...
    'Position',textWMPosition);
textScalpPosition = [0.2 0.125+3*0.15 textW textH];
Hmain.optionsWM = uicontrol('parent',Hmain.optionsPanel,...
    'Style','text',...
    'Units','normalized',...
    'String','Scalp',...
    'HorizontalAlignment','left',...
    'FontWeight','bold',...
    'FontSize',10,...
    'Position',textScalpPosition);
textPtsPosition = [0.2 0.125+4*0.15 textW textH];
Hmain.optionsWM = uicontrol('parent',Hmain.optionsPanel,...
    'Style','text',...
    'Units','normalized',...
    'String','Points',...
    'HorizontalAlignment','left',...
    'FontWeight','bold',...
    'FontSize',10,...
    'Position',textPtsPosition);

cbW = 0.2;
cbH = 0.15;
cbCoordsPosition = [0.6 0.125 cbW cbH];
Hmain.cbCoords = uicontrol('Parent',Hmain.optionsPanel,...
    'Style','checkbox',...
    'Units','normalized',...
    'Callback',@refreshViews,...
    'Enable','on',...
    'FontWeight','bold',...
    'FontSize',10,...
    'Position',cbCoordsPosition);
cbGMPosition = [0.6 0.125+0.15 cbW cbH];
Hmain.cbGM = uicontrol('Parent',Hmain.optionsPanel,...
    'Style','checkbox',...
    'Units','normalized',...
    'Callback',@refreshViews,...
    'FontWeight','bold',...
    'Enable','on',...
    'FontSize',10,...
    'Position',cbGMPosition);
cbWMPosition = [0.6 0.125+2*0.15 cbW cbH];
Hmain.cbWM = uicontrol('Parent',Hmain.optionsPanel,...
    'Style','checkbox',...
    'Units','normalized',...
    'Callback',@refreshViews,...
    'Enable','on',...
    'FontWeight','bold',...
    'FontSize',10,...
    'Position',cbWMPosition);
cbScalpPosition = [0.6 0.125+3*0.15 cbW cbH];
Hmain.cbScalp = uicontrol('Parent',Hmain.optionsPanel,...
    'Style','checkbox',...
    'Units','normalized',...
    'Callback',@refreshViews,...
    'Enable','on',...
    'FontWeight','bold',...
    'FontSize',10,...
    'Position',cbScalpPosition);
cbPtsPosition = [0.6 0.125+4*0.15 cbW cbH];
Hmain.cbPts = uicontrol('Parent',Hmain.optionsPanel,...
    'Style','checkbox',...
    'Units','normalized',...
    'Callback',@refreshViews,...
    'Enable','on',...
    'FontWeight','bold',...
    'FontSize',10,...
    'Position',cbPtsPosition);

%% Probe Panel
probeW = 0.18;
probeH = 0.94;
probePosition = [0.79 0.03 probeW probeH];
Hmain.probePanel = uipanel('parent',Hmain.mainFigure,...
    'Units','normalized',...
    'FontSize',10,...
    'Position',probePosition);

buttonW = 0.94;
buttonH = 0.05;
buttonPosition = [0.03 0.94 buttonW buttonH];
Hmain.buttonProbe = uicontrol('parent',Hmain.probePanel,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String','Load Probe',...
    'HorizontalAlignment','center',...
    'Enable','on',...
    'FontWeight','bold',...
    'FontSize',12,...
    'Position',buttonPosition,...
    'Callback', @loadProbe);
probeW = 0.94;
probeH = 0.15;
probePosition = [0.03 0.78 probeW probeH];
Hmain.axisProbe = axes('parent',Hmain.probePanel,...
    'Units','normalized',...
    'Position', probePosition,...
    'XDir','normal','YDir','normal',...
    'Box','off', ...
    'XGrid','off','YGrid','off',...
    'XTickLabel',[],'YTickLabel',[],...
    'Fontsize',6,...
    'Color',[1 1 1]/255,...
    'Box','off',...
    'Visible','on');

anchorW = 0.94;
anchorH = 0.25;
anchorPosition = [0.03 0.52 anchorW anchorH];
Hmain.anchorPanel = uipanel('parent',Hmain.probePanel,...
    'Units','normalized',...
    'FontSize',10,...
    'Position',anchorPosition);
textW = 0.45;
textH = 0.1;
textPosition = [0.01 0.7 textW textH];
Hmain.anchorText = uicontrol('parent',Hmain.anchorPanel,...
    'Style','text',...
    'Units','normalized',...
    'String','Anchor',...
    'HorizontalAlignment','Center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'Position',textPosition);
textPosition = [0.45 0.8 textW textH];
Hmain.anchorX = uicontrol('parent',Hmain.anchorPanel,...
    'Style','text',...
    'Units','normalized',...
    'String','x = ',...
    'HorizontalAlignment','Left',...
    'FontSize',12,...
    'Position',textPosition);
textPosition = [0.45 0.7 textW textH];
Hmain.anchorY = uicontrol('parent',Hmain.anchorPanel,...
    'Style','text',...
    'Units','normalized',...
    'String','y = ',...
    'HorizontalAlignment','Left',...
    'FontSize',12,...
    'Position',textPosition);
textPosition = [0.45 0.6 textW textH];
Hmain.anchorZ = uicontrol('parent',Hmain.anchorPanel,...
    'Style','text',...
    'Units','normalized',...
    'String','z = ',...
    'HorizontalAlignment','Left',...
    'FontSize',12,...
    'Position',textPosition);
popupW = 0.9;
popupH = 0.1;
popupPosition = [0.05 0.35 popupW popupH];
Hmain.anchorPopup = uicontrol('parent',Hmain.anchorPanel,...
    'Style','popupmenu',...
    'Units','normalized',...
    'String','Pick from 10-5',...
    'HorizontalAlignment','Left',...
    'FontWeight','bold',...
    'FontSize',8,...
    'Value', 1, ...
    'Position',popupPosition,...
    'Callback', @getAnchor);

selectW = 0.9;
selectH = 0.1;
selectPosition = [0.05 0.1 selectW selectH];
Hmain.anchorSelection = uicontrol('parent',Hmain.anchorPanel,...
    'Style','text',...
    'Units','normalized',...
    'String','Select a point',...
    'HorizontalAlignment','Left',...
    'FontWeight','bold',...
    'FontSize',8,...
    'Value', 1, ...
    'Position',selectPosition);

arrowW = 0.2;
arrowH = 0.1;
arrowPosition = [0.65 0.1 arrowW arrowH];
Hmain.anchorArrow = uicontrol('parent',Hmain.anchorPanel,...
    'Style','pushbutton',...
    'Units','normalized',...
    'FontName','Blue Highway',...
    'String',char(60),...
    'HorizontalAlignment','Right',...
    'FontWeight','bold',...
    'FontSize',12,...
    'Position',arrowPosition,...
    'Callback', @getdatacursorvalue);

buttonW = 0.94;
buttonH = 0.05;
buttonPosition = [0.03 0.01 buttonW buttonH];
Hmain.buttonAtlas = uicontrol('parent',Hmain.probePanel,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String','Load Atlas',...
    'HorizontalAlignment','center',...
    'Enable','on',...
    'FontWeight','bold',...
    'FontSize',12,...
    'Position',buttonPosition,...
    'Callback', @loadAtlas);

%% Nested Functions
    function loadButton(~,~)
        set(Hmain.cbGM, 'Enable', 'on');
        set(Hmain.cbWM, 'Enable', 'on');
        set(Hmain.cbScalp, 'Enable', 'on');
        set(Hmain.cbPts, 'Enable', 'on');
        %set(Hmain.rotateS, 'Enable', 'on');
        
        set(Hmain.cbGM, 'Value', 1);
        set(Hmain.cbWM, 'Value', 1);
        set(Hmain.cbScalp, 'Value', 1);
        set(Hmain.cbPts, 'Value', 0);
        set(Hmain.cbCoords, 'Value', 1);
    end

    function refreshViews(~,~)
        cbGM = get(Hmain.cbGM, 'Value');
        cbWM = get(Hmain.cbWM, 'Value');
        cbSc = get(Hmain.cbScalp, 'Value');
        cbPts = get(Hmain.cbPts, 'Value');
        cbCoords = get(Hmain.cbCoords, 'Value');

        alldata = Hmain.alldata;
        
        set(Hmain.anchorPopup, 'String', {alldata.RefPts{:,1}});
        
        [Hmain.AZ, Hmain.EL] = view;
        cla(Hmain.axis);
        if cbGM
            surf_GM_alpha = .3;
            surf_GM_color = 'y';
            axes(Hmain.axis)
            viewsurf(alldata.GM, surf_GM_alpha, surf_GM_color, 'off', [1 2 3])
        end
        hold on
        if cbWM
            surf_WM_alpha = .3;
            surf_WM_color = 'r';
            axes(Hmain.axis)
            viewsurf(alldata.WM, surf_WM_alpha, surf_WM_color, 'off', [1 2 3])
        end
        if cbSc
            surf_Scalp_alpha = .1;
            surf_Scalp_color = 'g';
            axes(Hmain.axis)
            viewsurf(alldata.Scalp, surf_Scalp_alpha, surf_Scalp_color, 'off', [1 2 3])
        end
        if cbPts
            axes(Hmain.axis)
            for aa = 1:1:length(alldata.RefPts)
                %text(alldata.RefPts{aa,2},alldata.RefPts{aa,3},alldata.RefPts{aa,4},alldata.RefPts{aa,1});
                plot3(alldata.RefPts{aa,2},alldata.RefPts{aa,3},alldata.RefPts{aa,4},'.r');
            end
%             for bb = 1:1:length(alldata.RefPts_partial)
%                 plot3(alldata.RefPts_partial{bb,2},alldata.RefPts_partial{bb,3},alldata.RefPts_partial{bb,4},'.b')
%             end
        end
        if cbCoords
            axes(Hmain.axis)
            
            S = [0,0,100];
            I = [0,0,-100];
            P = [0,-100,0];
            A = [0,100,0];
            R = [100,0,0];
            L = [-100,0,0];
            SI = [S; I];
            LR = [L; R];
            AP = [A; P];
            
            line(SI(:,1), SI(:,2), SI(:,3), 'LineWidth', 2, 'Color', [.8 .8 .8]);
            text(S(1), S(2), S(3), ' S', 'Color', 'w', 'Fontsize', 20, 'Fontweight', 'bold');
            text(I(1), I(2), I(3), ' I', 'Color', 'w', 'Fontsize', 20, 'Fontweight', 'bold');
            line(LR(:,1), LR(:,2), LR(:,3), 'LineWidth', 2, 'Color', [.8 .8 .8]);
            text(L(1), L(2), L(3), ' L', 'Color', 'w', 'Fontsize', 20, 'Fontweight', 'bold');
            text(R(1), R(2), R(3), ' R', 'Color', 'w', 'Fontsize', 20, 'Fontweight', 'bold');
            line(AP(:,1), AP(:,2), AP(:,3), 'LineWidth', 2, 'Color', [.8 .8 .8]);
            text(A(1), A(2), A(3), ' A', 'Color', 'w', 'Fontsize', 20, 'Fontweight', 'bold');
            text(P(1), P(2), P(3), ' P', 'Color', 'w', 'Fontsize', 20, 'Fontweight', 'bold');
        end
        
        rotate3d on
        view(Hmain.AZ, Hmain.EL)
       
        axis off
        axis equal
        %axis([-50 50 -100 50 -40 80]);
        axis([-100 100 -100 100 -100 100]);
    end

    function rotateS(~,~)
        Hmain.AZ = 0;
        Hmain.EL = 90;
        axes(Hmain.axis)
        view(Hmain.AZ, Hmain.EL)
        refreshViews;
    end
    function rotateI(~,~)
        Hmain.AZ = 0;
        Hmain.EL = -90;
        axes(Hmain.axis)
        view(Hmain.AZ, Hmain.EL)
        refreshViews;
    end
    function rotateL(~,~)
        Hmain.AZ = -90;
        Hmain.EL = 0;
        axes(Hmain.axis)
        view(Hmain.AZ, Hmain.EL)
        refreshViews;
    end
    function rotateR(~,~)
        Hmain.AZ = 90;
        Hmain.EL = 0;
        axes(Hmain.axis)
        view(Hmain.AZ, Hmain.EL)
        refreshViews;
    end
    function rotateA(~,~)
        Hmain.AZ = 180;
        Hmain.EL = 0;
        axes(Hmain.axis)
        view(Hmain.AZ, Hmain.EL)
        refreshViews;
    end
    function rotateP(~,~)
        Hmain.AZ = 0;
        Hmain.EL = 0;
        axes(Hmain.axis)
        view(Hmain.AZ, Hmain.EL)
        refreshViews;
    end

    function loadProbe(~,~)
        [filename, pathname] = uigetfile({'*.*','All Files (*.*)'}, 'Pick a file');
        probe = load([pathname,filename],'-mat');
        xmin = min([probe.SrcPos(:,1);probe.DetPos(:,1)])*1.2;
        xmax = max([probe.SrcPos(:,1);probe.DetPos(:,1)])*1.2;
        ymin = min([probe.SrcPos(:,2);probe.DetPos(:,2)])*1.2;
        ymax = max([probe.SrcPos(:,2);probe.DetPos(:,2)])*1.2;
        zmin = min([probe.SrcPos(:,3);probe.DetPos(:,3)])*1.2;
        zmax = max([probe.SrcPos(:,3);probe.DetPos(:,3)])*1.2;
        if zmax==zmin
            zmin = -10;
            zmax = 10;
        end
        cla(Hmain.axisProbe);
        axes(Hmain.axisProbe);
        plot3(probe.SrcPos(:,1), probe.SrcPos(:,2), probe.SrcPos(:,3), ...
            'Marker', 'o', 'MarkerEdgeColor', 'k', 'MarkerFaceColor', 'r', ...
            'LineStyle', 'none')
        hold on
        plot3(probe.DetPos(:,1), probe.DetPos(:,2), probe.DetPos(:,3), ...
            'Marker', 'o', 'MarkerEdgeColor', 'k', 'MarkerFaceColor', 'b', ...
            'LineStyle', 'none')
        view(-90,90)
        axis([xmin xmax ymin ymax zmin zmax])
        axis equal
        axis off
    end

    function getAnchor(~,~)
        alldata = Hmain.alldata;
        set(Hmain.anchorX, 'String', ['x = ' num2str(alldata.RefPts{get(Hmain.anchorPopup, 'Value'), 2})]);
        set(Hmain.anchorY, 'String', ['y = ' num2str(alldata.RefPts{get(Hmain.anchorPopup, 'Value'), 3})]);
        set(Hmain.anchorZ, 'String', ['z = ' num2str(alldata.RefPts{get(Hmain.anchorPopup, 'Value'), 4})]);
    end

    function getdatacursorvalue(~,~)
        dcm_obj = datacursormode(Hmain.mainFigure);
        set(dcm_obj, 'DisplayStyle', 'datatip', 'SnapToDataVertex', 'off', 'Enable', 'on')
        pause;
        pos = getCursorInfo(dcm_obj);
        pos = pos.Position;
        set(Hmain.anchorX, 'String', ['x = ' num2str(round(pos(1),2))]);
        set(Hmain.anchorY, 'String', ['y = ' num2str(round(pos(2),2))]);
        set(Hmain.anchorZ, 'String', ['z = ' num2str(round(pos(3),2))]);
        datacursormode off
    end

    function loadAtlas(~,~)
        Hmain.alldata = load('atlas_40weeks.mat');
        %Hmain.alldata = load('atlas_40weeks_partial.mat');
        refreshViews;
    end
        

%% Turn on!
loadButton;
set(Hmain.mainFigure,'Visible','on');
end